<a href="https://colab.research.google.com/github/MadhawaAponso/DataVisulaization_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LEARN NUMPY

## NumPy

### Why NumPy?

NumPy is a fundamental library in Python for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is particularly useful for scientific computing because it allows for fast array processing, leveraging optimized C code under the hood, making operations much faster than using Python's native lists.

**Key reasons for using NumPy:**
- **Performance**: Faster computations on large datasets.
- **Convenience**: Simplifies operations like matrix multiplication, statistical calculations, and reshaping arrays.
- **Integration**: Works well with other libraries like SciPy, Pandas, and Matplotlib for data analysis and visualization.

---

### What are we covering here?

This notebook will cover the following topics:
- **Most useful functions**
- **NumPy data types and attributes**
- **Creating arrays**
- **Viewing arrays and matrices**
- **Manipulating and comparing arrays**
- **Sorting arrays**
- **Use cases**

By the end of this notebook, you will be familiar with NumPy's most important features and capable of applying it to a wide range of data-related tasks.

---

## Importing NumPy
Start by importing NumPy:

```python
import numpy as np


In [61]:
import numpy as np

#1. Data Types and Attributes
NumPy arrays are called ndarrays (N-dimensional arrays). Let's explore how to create and inspect basic arrays.

In [ ]:
# Creating different types of arrays
a1 = np.array([1, 2, 3])  # 1D array
a2 = np.array([[1, 2, 3], [2, 3, 4]])  # 2D array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[12, 23, 34], [45, 54, 23]]])  # 3D array


In [62]:
#Checking the types and shapes
# Type of the array
type(a1)

# Shape of the arrays
print(a2.shape)  # Output: (2, 3)
print(a3.shape)  # Output: (2, 2, 3)

# Size: Total number of elements in the arrays
print(a1.size, a2.size, a3.size)


(2, 3)
(2, 2, 3)
3 6 12


#2. Creating Arrays
NumPy provides several ways to create arrays from scratch:

In [63]:
# Simple array
sample_array = np.array([1, 2, 3])

# Array of ones
array_with_ones = np.ones((2, 3))
print(array_with_ones)

# Array of zeros
#np.ones() and np.zeros(): Create arrays filled with 1s and 0s.
array_with_zeros = np.zeros((2, 3))
print(array_with_zeros)

# Array with a range of numbers
#np.arange(): Create an array with evenly spaced values.
range_array = np.arange(0, 10, 2)
print(range_array)

# Random arrays
# np.random.rand(): Generates random numbers between 0 and 1.
random_array = np.random.rand(2, 3)
print(random_array)

# Random integers
# Generates random integers within a specified range.
rand_int_array = np.random.randint(0, 10, size=(2, 3))
print(rand_int_array)

# Setting a seed for reproducibility
np.random.seed(42)
r_a = np.random.rand(2, 3)
print(r_a)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[[0.81801477 0.86073058 0.00695213]
 [0.5107473  0.417411   0.22210781]]
[[2 9 7]
 [5 7 8]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


#3. Viewing Arrays and Matrices
You can index and slice arrays to view specific elements:

In [64]:
# Accessing elements in arrays
print(a1[0])  # First element of 1D array
print(a2[0])  # First row of 2D array
print(a3[0])  # First 2D array from the 3D array


1
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [65]:
#Advance indexing
r_a1 = np.random.rand(2, 3, 4, 5)
print(r_a1[1][1][:, 2])  # Nested indexing
print(r_a1[1, 1, :, 2])  # Same as above, more efficient

[0.88721274 0.5612772  0.02541913 0.50857069]
[0.88721274 0.5612772  0.02541913 0.50857069]


# 4. Manipulating and Comparing Arrays
You can easily perform arithmetic operations on NumPy arrays:

In [66]:
# Element-wise operations
ones = np.ones(3)
print(a1 + ones)  # Addition
print(a1 - ones)  # Subtraction
print(a1 * ones)  # Multiplication

# Multiplying arrays
print(a2 * a1)  # Broadcasting example

# Reshaping arrays
reshaped_a2 = a2.reshape((2, 3, 1, 1))
print(reshaped_a2)

# Multiply reshaped array
result = reshaped_a2 * r_a1
print(result)


[2. 3. 4.]
[0. 1. 2.]
[1. 2. 3.]
[[ 1  4  9]
 [ 2  6 12]]
[[[[1]]

  [[2]]

  [[3]]]


 [[[2]]

  [[3]]

  [[4]]]]
[[[[0.05808361 0.86617615 0.60111501 0.70807258 0.02058449]
   [0.96990985 0.83244264 0.21233911 0.18182497 0.18340451]
   [0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
   [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596]]

  [[0.39934756 1.02846888 1.18482914 0.09290083 1.2150897 ]
   [0.34104825 0.13010319 1.89777107 1.93126407 1.6167947 ]
   [0.60922754 0.19534423 1.36846605 0.88030499 0.24407647]
   [0.99035382 0.06877704 1.8186408  0.51755996 1.32504457]]

  [[0.93513323 1.56020406 1.64013084 0.55456337 2.90875388]
   [2.32539847 2.81849682 2.68448205 1.79369994 2.76562271]
   [0.26547751 0.58794859 0.13568187 0.97599099 1.16603187]
   [0.8140471  2.48621253 1.07025998 0.84280353 1.62808825]]]


 [[[0.28184845 1.60439396 0.14910129 1.97377387 1.54448954]
   [0.39743136 0.01104423 1.63092286 1.41371469 1.45801434]
   [1.54254069 0.1480893  0.71693146 

# 5. Sorting Arrays

In [67]:
# Sorting an array
sorted_array = np.sort(a1)
print(sorted_array)

# Sorting along an axis
sorted_a2 = np.sort(a2, axis=0)
print(sorted_a2)


[1 2 3]
[[1 2 3]
 [2 3 4]]


# 6. Reshaping and Transposing Arrays

In [68]:
# Reshape an array
reshaped_a1 = a1.reshape((3, 1))
print(reshaped_a1)

# Transpose an array (switch rows and columns)
transposed_a2 = a2.T
print(transposed_a2)


[[1]
 [2]
 [3]]
[[1 2]
 [2 3]
 [3 4]]


# 7. Mathematical Operations

In [69]:
# Basic functions
print(np.mean(a1))  # Mean
print(np.max(a2))   # Maximum
print(np.min(a2))   # Minimum
print(np.sum(a2))   # Sum of elements

# Standard deviation and variance
print(np.std(a2))   # Standard deviation
print(np.var(a2))   # Variance

# Dot product
print(np.dot(a1, a1))  # Dot product of two vectors


2.0
4
1
15
0.9574271077563381
0.9166666666666666
14
